### ISSUE TITLE
A couple of errors

### ISSUE THREAD

**Issue by rubylaser** [SmileyMan/snapPERL#1]
Hello Steve,

I decided to give your script a run today on some test data.  I hit a couple of snags I wanted to share with you.  As soon as I ran the script, I had a couple of errors right away.

``` errors
root@fileserver:~/scripts# perl snapPERL.pl
15:58:54 - Tue 3 May 2016 : Script Started
Use of uninitialized value $value in substitution (s///) at snapPERL.pl line 437.
Use of uninitialized value $value in pattern match (m//) at snapPERL.pl line 451.
```

Also, the script doesn't seem to handle some special characters (I'm assuming the exclamation points).  Here's what I saw when it hit those files.

``` bash
Error opening file '/mnt/data/disk06/anime/Durarara!!/Season 2/Durarara!! - S02E04 - 029 - When in Rome, Do as the Romans Do.mkv'. No such file or directory.
Error opening file '/mnt/data/disk06/anime/Durarara!!/Season 2/Durarara!! - S02E06 - 031 - A Crow in the Dark Night.mkv'. No such file or directory.
Error opening file '/mnt/data/disk06/anime/Durarara!!/Season 2/Durarara!! - S02E08 - 033 - The Ladies' Man Has Neither Money Nor Power.mkv'. No such file or directory.
Error opening file '/mnt/data/disk06/anime/Durarara!!/Season 2/Durarara!! - S02E07 - 032 - Moscow Does Not Believe in Tears.mkv'. No such file or directory.
Error opening file '/mnt/data/disk06/anime/Durarara!!/Season 2/Durarara!! - S02E11 - 036 - No Use Crying Over Spilt Milk.mkv'. No such file or directory.
```

The files listed above read and sync fine with snapraid diff/sync and are handled properly with the current BASH script.  I look forward to seeing how this script turns out :)  Thanks for your hard work!

**Comment by SmileyMan** [comment]
The first errors may just be a bad buggy commit I did last night. Same thing happens with latest version? 

_Looking again can you post the snapraid.conf file you are using. Think you have empty values and I need to check for this in the script._

The file errors have got me. Script is just a wrapper around snapraid.exe so only reads conf file and writes log file. Strange. Script never reads or manipulates any of the array data?

_Looking at this. Script only catches snapraid.exe stdout.. it's errors will go to stderr and show in terminal? You don't get the file errors on you test data running snapraid diff|sync|scrub manually?_

I need to catch and process stderr from snapraid I think.

Have a go with latest version and set logging to 5 and logStdout to 1 and post me the log thanks.

**Comment by SmileyMan** [comment]
Latest commit loads modules for email support. You can comment them out for the moment. Email not done and need to change this to load as needed.

**Comment by rubylaser** [comment]
Sure, here is my snapraid.conf.  I don't have any missing values.

``` bash
root@fileserver:~/scripts# cat /etc/snapraid.conf
# Parity
parity /mnt/parity/1-parity/snapraid.parity
2-parity /mnt/parity/2-parity/snapraid.q-parity
3-parity /mnt/parity/3-parity/snapraid.r-parity
#4-parity /mnt/disks/s-parity # 4 parity disks
#5-parity /mnt/diskt/t-parity # 5 parity disks
#6-parity /mnt/disku/u-parity # 6 parity disks

# Defines the files to use as content list
# You can use multiple specification to store more copies
# You must have least one copy for each parity file plus one. Some more don't hurt
# They can be in the disks used for data, parity or boot,
# but each file must be in a different disk
# Format: "content FILE_PATH"
content /var/snapraid/content
content /mnt/data/disk01/content
content /mnt/data/disk02/content
content /mnt/data/disk03/content
content /mnt/data/disk04/content
content /mnt/data/disk05/content
content /mnt/data/disk06/content
content /mnt/data/disk07/content
content /mnt/data/disk08/content
content /mnt/data/disk09/content
content /mnt/data/disk10/content
content /mnt/data/disk11/content
content /mnt/data/disk12/content
content /mnt/data/disk13/content
content /mnt/data/disk14/content
content /mnt/data/disk15/content

# Defines the data disks to use
# The order is relevant for parity, do not change it
# Format: "disk DISK_NAME DISK_MOUNT_POINT"
disk d01 /mnt/data/disk01
disk d02 /mnt/data/disk02
disk d03 /mnt/data/disk03
disk d04 /mnt/data/disk04
disk d05 /mnt/data/disk05
disk d06 /mnt/data/disk06
disk d07 /mnt/data/disk07
disk d08 /mnt/data/disk08
disk d09 /mnt/data/disk09
disk d10 /mnt/data/disk10
disk d11 /mnt/data/disk11
disk d12 /mnt/data/disk12
disk d13 /mnt/data/disk13
disk d14 /mnt/data/disk14
disk d15 /mnt/data/disk15

# Excludes hidden files and directories (uncomment to enable).
nohidden

# Defines files and directories to exclude
# Remember that all the paths are relative at the mount points
# Format: "exclude FILE"
# Format: "exclude DIR/"
# Format: "exclude /PATH/FILE"
# Format: "exclude /PATH/DIR/"
exclude *.bak
exclude *.unrecoverable
exclude /tmp/
exclude /lost+found/
exclude *.!sync
exclude .AppleDouble
exclude ._AppleDouble
exclude .DS_Store
exclude ._.DS_Store
exclude .Thumbs.db
exclude .fseventsd
exclude .Spotlight-V100
exclude .TemporaryItems
exclude .Trashes
exclude .AppleDB
exclude /.trash/

# Defines the block size in kibi bytes (1024 bytes).
# Default value is 256 -> 256 kibi bytes -> 262144 bytes
# Format: "block_size SIZE_IN_KiB"
blocksize 256
```

**Comment by SmileyMan** [comment]
Yeah the conf looks fine. 

Can you run the latest commit so I can get the lines with the uninitialized values and debug.

The file read errors concerns me. What snapraid command was being run when they popped u?

**Comment by rubylaser** [comment]
I set the logging level to 5, but I don't have a log at /tmp/script-snapRAID.log.  It was running the sync when the errors showed up. 

Edit: I ran a full diff/sync by hand so that SnapRAID was all up to date.  Then, I manually created a file and I'm trying the script again.   I'm still not seeing a logfile being created, but this time the script seems to be running other than the errors from the beginning.

``` bash
Use of uninitialized value $value in substitution (s///) at snapPERL.pl line 448.
Use of uninitialized value $value in pattern match (m//) at snapPERL.pl line 462.
```

It's running a scrub right now, so I'll let that finish :)

**Comment by SmileyMan** [comment]
https://github.com/SmileyMan/snapPERL/commit/90ea55869f2ffda80529b0b84d307113e2c174d6

Latest commit will fix those uninitialized warnings.

Log is only created when script finishes. If you set logStdout=1 the it will also show in terminal.

If still no log and using this commit let us know. Works on my machine so will need to work out whats different. Also what user do you run it under (assuming root?)

**Comment by rubylaser** [comment]
Thanks, it was laziness on my part that I didn't catch the logStdout variable.  I had already fixed that, but not edited my reply.  Also, I tried the latest version this morning and the uninitialized warnings are gone :)

**Comment by SmileyMan** [comment]
Nice.

Just enabling email support in Dev branch. Will merge when working (Gmail send at least)

_Gmail email send working on Dev branch. Works good..._

**Comment by rubylaser** [comment]
Awesome!  I also like the separation of the config file from the script itself.  This will make pulling future updates easier without overwriting custom config options.  

Another thing to potentially add to your todo would be to add the ability to pause and unpause docker containers so that data isn't written to the array while a sync/scrub is happening.  I have added these at the beginning of my BASH script.

``` bash
docker pause nzbget
```

and this at the end...

``` bash
docker unpause nzbget
```

**Comment by SmileyMan** [comment]
Added to  Todo.

**Comment by SmileyMan** [comment]
Custom commands done! :P

**Comment by rubylaser** [comment]
Woo hoo!  I'll check it out tonight if I get a chance.  Thanks again!
