### ISSUE TITLE
Script indicates file error - status shows all OK

### ISSUE THREAD

**Issue by mtompkins** [SmileyMan/snapPERL#19]
Somewhere between a bug report and an FYI - as it is hard to identify if there is a problem with your wrapper script or `snapraid`, however in the logs captured by your script (on multiple occasions now) ...

```
      1 file errors
       0 io errors
       0 data errors
Saving state to /var/snapraid.content...
Saving state to /mnt/data/disk1/snapraid.content...
Saving state to /mnt/data/disk2/snapraid.content...
  189231 files
       0 hardlinks
       1 symlinks
   76208 empty dirs
Verifying /var/snapraid.content...
Verifying /mnt/data/disk1/snapraid.content...
Verifying /mnt/data/disk2/snapraid.content... 
```

and an immediate `snapraid status` claims no issues:

```
No sync is in progress.
The 1% of the array is not scrubbed.
No file has a zero sub-second timestamp.
No rehash is in progress or needed.
No error detected.
```

I've been unable to reproduce this outside of using the script. Direct calls to `snapraid` complete without issue.

I know how little help this is, but am sharing what I discover as I am able.

**Comment by mtompkins** [comment]
Found the issue, was an automated process deleting a file during the scrub.
Not a script issue.

**Comment by SmileyMan** [comment]
Yeah stop everything that uses the array during the sync.

This is a snapraid warning about things changing during sync. Snapraid does cope well with this but its not recommended

Steve

P.s. sorry for late reply - 5 month old and new job have me tied up
